name: 🚀 Deploy to hub.ondeon.es

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 📂 Deploy via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: 📂 Deploy to IONOS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            CNAME
            README.md
            .ftp-deploy-sync-state.json
